Class {
	#name : #DartContinueStatementNode,
	#superclass : #DartStatementNode,
	#instVars : [
		'continueToken',
		'semicolonToken',
		'identifierToken',
		'abstractToken',
		'asToken',
		'covariantToken',
		'deferredToken',
		'dynamicToken',
		'exportToken',
		'extensionToken',
		'externalToken',
		'factoryToken',
		'functionToken',
		'getToken',
		'implementsToken',
		'importToken',
		'interfaceToken',
		'lateToken',
		'libraryToken',
		'operatorToken',
		'mixinToken',
		'partToken',
		'requiredToken',
		'setToken',
		'staticToken',
		'typedefToken',
		'asyncToken',
		'hideToken',
		'ofToken',
		'onToken',
		'showToken',
		'syncToken',
		'awaitToken',
		'yieldToken'
	],
	#category : #'SmaCC_Dart'
}

{ #category : #generated }
DartContinueStatementNode >> abstractToken [

	^ abstractToken
]

{ #category : #generated }
DartContinueStatementNode >> abstractToken: aSmaCCToken [

	abstractToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> acceptVisitor: aProgramVisitor [

	^ aProgramVisitor visitContinueStatement: self
]

{ #category : #generated }
DartContinueStatementNode >> asToken [

	^ asToken
]

{ #category : #generated }
DartContinueStatementNode >> asToken: aSmaCCToken [

	asToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> asyncToken [

	^ asyncToken
]

{ #category : #generated }
DartContinueStatementNode >> asyncToken: aSmaCCToken [

	asyncToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> awaitToken [

	^ awaitToken
]

{ #category : #generated }
DartContinueStatementNode >> awaitToken: aSmaCCToken [

	awaitToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> continueToken [

	^ continueToken
]

{ #category : #generated }
DartContinueStatementNode >> continueToken: aSmaCCToken [

	continueToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> covariantToken [

	^ covariantToken
]

{ #category : #generated }
DartContinueStatementNode >> covariantToken: aSmaCCToken [

	covariantToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> deferredToken [

	^ deferredToken
]

{ #category : #generated }
DartContinueStatementNode >> deferredToken: aSmaCCToken [

	deferredToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> dynamicToken [

	^ dynamicToken
]

{ #category : #generated }
DartContinueStatementNode >> dynamicToken: aSmaCCToken [

	dynamicToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> exportToken [

	^ exportToken
]

{ #category : #generated }
DartContinueStatementNode >> exportToken: aSmaCCToken [

	exportToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> extensionToken [

	^ extensionToken
]

{ #category : #generated }
DartContinueStatementNode >> extensionToken: aSmaCCToken [

	extensionToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> externalToken [

	^ externalToken
]

{ #category : #generated }
DartContinueStatementNode >> externalToken: aSmaCCToken [

	externalToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> factoryToken [

	^ factoryToken
]

{ #category : #generated }
DartContinueStatementNode >> factoryToken: aSmaCCToken [

	factoryToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> functionToken [

	^ functionToken
]

{ #category : #generated }
DartContinueStatementNode >> functionToken: aSmaCCToken [

	functionToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> getToken [

	^ getToken
]

{ #category : #generated }
DartContinueStatementNode >> getToken: aSmaCCToken [

	getToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> hideToken [

	^ hideToken
]

{ #category : #generated }
DartContinueStatementNode >> hideToken: aSmaCCToken [

	hideToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> identifierToken [

	^ identifierToken
]

{ #category : #generated }
DartContinueStatementNode >> identifierToken: aSmaCCToken [

	identifierToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> implementsToken [

	^ implementsToken
]

{ #category : #generated }
DartContinueStatementNode >> implementsToken: aSmaCCToken [

	implementsToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> importToken [

	^ importToken
]

{ #category : #generated }
DartContinueStatementNode >> importToken: aSmaCCToken [

	importToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> interfaceToken [

	^ interfaceToken
]

{ #category : #generated }
DartContinueStatementNode >> interfaceToken: aSmaCCToken [

	interfaceToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> lateToken [

	^ lateToken
]

{ #category : #generated }
DartContinueStatementNode >> lateToken: aSmaCCToken [

	lateToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> libraryToken [

	^ libraryToken
]

{ #category : #generated }
DartContinueStatementNode >> libraryToken: aSmaCCToken [

	libraryToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> mixinToken [

	^ mixinToken
]

{ #category : #generated }
DartContinueStatementNode >> mixinToken: aSmaCCToken [

	mixinToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> ofToken [

	^ ofToken
]

{ #category : #generated }
DartContinueStatementNode >> ofToken: aSmaCCToken [

	ofToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> onToken [

	^ onToken
]

{ #category : #generated }
DartContinueStatementNode >> onToken: aSmaCCToken [

	onToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> operatorToken [

	^ operatorToken
]

{ #category : #generated }
DartContinueStatementNode >> operatorToken: aSmaCCToken [

	operatorToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> partToken [

	^ partToken
]

{ #category : #generated }
DartContinueStatementNode >> partToken: aSmaCCToken [

	partToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> requiredToken [

	^ requiredToken
]

{ #category : #generated }
DartContinueStatementNode >> requiredToken: aSmaCCToken [

	requiredToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> semicolonToken [

	^ semicolonToken
]

{ #category : #generated }
DartContinueStatementNode >> semicolonToken: aSmaCCToken [

	semicolonToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> setToken [

	^ setToken
]

{ #category : #generated }
DartContinueStatementNode >> setToken: aSmaCCToken [

	setToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> showToken [

	^ showToken
]

{ #category : #generated }
DartContinueStatementNode >> showToken: aSmaCCToken [

	showToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> staticToken [

	^ staticToken
]

{ #category : #generated }
DartContinueStatementNode >> staticToken: aSmaCCToken [

	staticToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> syncToken [

	^ syncToken
]

{ #category : #generated }
DartContinueStatementNode >> syncToken: aSmaCCToken [

	syncToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> tokenVariables [

	^ #( #continueToken #semicolonToken #identifierToken #abstractToken
	     #asToken #covariantToken #deferredToken #dynamicToken
	     #exportToken #extensionToken #externalToken #factoryToken
	     #functionToken #getToken #implementsToken #importToken
	     #interfaceToken #lateToken #libraryToken #operatorToken
	     #mixinToken #partToken #requiredToken #setToken #staticToken
	     #typedefToken #asyncToken #hideToken #ofToken #onToken #showToken
	     #syncToken #awaitToken #yieldToken )
]

{ #category : #generated }
DartContinueStatementNode >> typedefToken [

	^ typedefToken
]

{ #category : #generated }
DartContinueStatementNode >> typedefToken: aSmaCCToken [

	typedefToken := aSmaCCToken
]

{ #category : #generated }
DartContinueStatementNode >> yieldToken [

	^ yieldToken
]

{ #category : #generated }
DartContinueStatementNode >> yieldToken: aSmaCCToken [

	yieldToken := aSmaCCToken
]
