Trait {
	#name : #TDartProgramNodeVisitor,
	#traits : 'TSmaCCParseNodeVisitor',
	#classTraits : 'TSmaCCParseNodeVisitor classTrait',
	#category : #'SmaCC_Dart'
}

{ #category : #generated }
TDartProgramNodeVisitor >> visitAdditiveExpression: anAdditiveExpression [

	^ self visitProgram: anAdditiveExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitArgumentList: anArgumentList [

	^ self visitProgram: anArgumentList
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitAssertStatement: anAssertStatement [

	^ self visitProgram: anAssertStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitAssertion: anAssertion [

	^ self visitProgram: anAssertion
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitAssignableExpression: anAssignableExpression [

	^ self visitProgram: anAssignableExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitAssignableExpressionWithOperator: anAssignableExpressionWithOperator [

	^ self visitProgram: anAssignableExpressionWithOperator
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitAssignableExpressionWithoutCascadeWithOperator: anAssignableExpressionWithoutCascadeWithOperator [

	^ self visitProgram: anAssignableExpressionWithoutCascadeWithOperator
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitAssignmentOperator: anAssignmentOperator [

	^ self visitProgram: anAssignmentOperator
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitAsyncFunctionBody: anAsyncFunctionBody [

	^ self visitProgram: anAsyncFunctionBody
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitAwaitExpression: anAwaitExpression [

	^ self visitProgram: anAwaitExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitBinaryExpression: aBinaryExpression [

	^ self visitProgram: aBinaryExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitBlock: aBlock [

	^ self visitProgram: aBlock
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitBooleanLiteral: aBooleanLiteral [

	^ self visitProgram: aBooleanLiteral
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitBreakStatement: aBreakStatement [

	^ self visitProgram: aBreakStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitCascade: aCascade [

	^ self visitProgram: aCascade
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitCatchPart: aCatchPart [

	^ self visitProgram: aCatchPart
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitClassDeclaration: aClassDeclaration [

	^ self visitProgram: aClassDeclaration
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitClassMemberDefinition: aClassMemberDefinition [

	^ self visitProgram: aClassMemberDefinition
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitConditionalExpression: aConditionalExpression [

	^ self visitProgram: aConditionalExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitConfigurableUri: aConfigurableUri [

	^ self visitProgram: aConfigurableUri
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitConfigurationUri: aConfigurationUri [

	^ self visitProgram: aConfigurationUri
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitConstObjectExpression: aConstObjectExpression [

	^ self visitProgram: aConstObjectExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitConstantConstructorSignature: aConstantConstructorSignature [

	^ self visitProgram: aConstantConstructorSignature
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitConstructorDesignation: aConstructorDesignation [

	^ self visitProgram: aConstructorDesignation
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitConstructorInvocation: aConstructorInvocation [

	^ self visitProgram: aConstructorInvocation
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitConstructorName: aConstructorName [

	^ self visitProgram: aConstructorName
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitConstructorSignature: aConstructorSignature [

	^ self visitProgram: aConstructorSignature
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitContinueStatement: aContinueStatement [

	^ self visitProgram: aContinueStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitDeclaration: aDeclaration [

	^ self visitProgram: aDeclaration
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitDeclaredIdentifier: aDeclaredIdentifier [

	^ self visitProgram: aDeclaredIdentifier
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitDefaultCase: aDefaultCase [

	^ self visitProgram: aDefaultCase
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitDoStatement: aDoStatement [

	^ self visitProgram: aDoStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitDottedIdentifierList: aDottedIdentifierList [

	^ self visitProgram: aDottedIdentifierList
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitElement: anElement [

	^ self visitProgram: anElement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitElements: anElements [

	^ self visitProgram: anElements
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitEnumEntry: anEnumEntry [

	^ self visitProgram: anEnumEntry
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitExportDeclaration: anExportDeclaration [

	^ self visitProgram: anExportDeclaration
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitExpressionElement: anExpressionElement [

	^ self visitProgram: anExpressionElement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitExpressionList: anExpressionList [

	^ self visitProgram: anExpressionList
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFactoryConstructorSignature: aFactoryConstructorSignature [

	^ self visitProgram: aFactoryConstructorSignature
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFieldFormalParameter: aFieldFormalParameter [

	^ self visitProgram: aFieldFormalParameter
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFieldInitializer: aFieldInitializer [

	^ self visitProgram: aFieldInitializer
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFinallyPart: aFinallyPart [

	^ self visitProgram: aFinallyPart
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitForStatement: aForStatement [

	^ self visitProgram: aForStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFormalParameterPart: aFormalParameterPart [

	^ self visitProgram: aFormalParameterPart
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFunctionBody: aFunctionBody [

	^ self visitProgram: aFunctionBody
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFunctionExpression: aFunctionExpression [

	^ self visitProgram: aFunctionExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFunctionFormalParameter: aFunctionFormalParameter [

	^ self visitProgram: aFunctionFormalParameter
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFunctionPrefix: aFunctionPrefix [

	^ self visitProgram: aFunctionPrefix
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFunctionSignature: aFunctionSignature [

	^ self visitProgram: aFunctionSignature
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFunctionType: aFunctionType [

	^ self visitProgram: aFunctionType
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFunctionTypeAlias: aFunctionTypeAlias [

	^ self visitProgram: aFunctionTypeAlias
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFunctionTypeTail: aFunctionTypeTail [

	^ self visitProgram: aFunctionTypeTail
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitFunctionTypeTails: aFunctionTypeTails [

	^ self visitProgram: aFunctionTypeTails
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitGetterSignature: aGetterSignature [

	^ self visitProgram: aGetterSignature
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitIdentifier: anIdentifier [

	^ self visitProgram: anIdentifier
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitIdentifierList: anIdentifierList [

	^ self visitProgram: anIdentifierList
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitIfNullExpression: anIfNullExpression [

	^ self visitProgram: anIfNullExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitIfStatement: anIfStatement [

	^ self visitProgram: anIfStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitImportSpecification: anImportSpecification [

	^ self visitProgram: anImportSpecification
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitInitializedIdentifier: anInitializedIdentifier [

	^ self visitProgram: anInitializedIdentifier
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitInitializedIdentifierList: anInitializedIdentifierList [

	^ self visitProgram: anInitializedIdentifierList
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitInitializedVariableDeclaration: anInitializedVariableDeclaration [

	^ self visitProgram: anInitializedVariableDeclaration
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitInitializerExpression: anInitializerExpression [

	^ self visitProgram: anInitializerExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitInitializers: anInitializers [

	^ self visitProgram: anInitializers
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitLabel: aLabel [

	^ self visitProgram: aLabel
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitLibraryDefinition: aLibraryDefinition [

	^ self visitProgram: aLibraryDefinition
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitLibraryImport: aLibraryImport [

	^ self visitProgram: aLibraryImport
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitLibraryName: aLibraryName [

	^ self visitProgram: aLibraryName
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitListLiteral: aListLiteral [

	^ self visitProgram: aListLiteral
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitLocalFunctionDeclaration: aLocalFunctionDeclaration [

	^ self visitProgram: aLocalFunctionDeclaration
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitLocalVariableDeclaration: aLocalVariableDeclaration [

	^ self visitProgram: aLocalVariableDeclaration
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitMetadatum: aMetadatum [

	^ self visitProgram: aMetadatum
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitMethodSignature: aMethodSignature [

	^ self visitProgram: aMethodSignature
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitMixinApplication: aMixinApplication [

	^ self visitProgram: aMixinApplication
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitMixinApplicationClass: aMixinApplicationClass [

	^ self visitProgram: aMixinApplicationClass
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitMultiLineString: aMultiLineString [

	^ self visitProgram: aMultiLineString
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitMultiplicativeExpression: aMultiplicativeExpression [

	^ self visitProgram: aMultiplicativeExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNamedArgument: aNamedArgument [

	^ self visitProgram: aNamedArgument
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNamedFormalParameters: aNamedFormalParameters [

	^ self visitProgram: aNamedFormalParameters
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNamedParameterType: aNamedParameterType [

	^ self visitProgram: aNamedParameterType
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNamedParameterTypes: aNamedParameterTypes [

	^ self visitProgram: aNamedParameterTypes
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNewExpression: aNewExpression [

	^ self visitProgram: aNewExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNormalFormalParameter: aNormalFormalParameter [

	^ self visitProgram: aNormalFormalParameter
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNormalFormalParameters: aNormalFormalParameters [

	^ self visitProgram: aNormalFormalParameters
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNormalParameterType: aNormalParameterType [

	^ self visitProgram: aNormalParameterType
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNormalParameterTypes: aNormalParameterTypes [

	^ self visitProgram: aNormalParameterTypes
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNullLiteral: aNullLiteral [

	^ self visitProgram: aNullLiteral
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitNumericLiteral: aNumericLiteral [

	^ self visitProgram: aNumericLiteral
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitOnPart: anOnPart [

	^ self visitProgram: anOnPart
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitOperatorSignature: anOperatorSignature [

	^ self visitProgram: anOperatorSignature
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitOptionalPositionalFormalParameters: anOptionalPositionalFormalParameters [

	^ self visitProgram: anOptionalPositionalFormalParameters
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitPartDeclaration: aPartDeclaration [

	^ self visitProgram: aPartDeclaration
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitPartDirective: aPartDirective [

	^ self visitProgram: aPartDirective
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitPartHeader: aPartHeader [

	^ self visitProgram: aPartHeader
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitPostfixExpression: aPostfixExpression [

	^ self visitProgram: aPostfixExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitPrimary: aPrimary [

	^ self visitProgram: aPrimary
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitProgram: aProgram [

	^ self visitSmaCCParseNode: aProgram
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitQualifiedName: aQualifiedName [

	^ self visitProgram: aQualifiedName
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitRedirectingFactoryConstructorSignature: aRedirectingFactoryConstructorSignature [

	^ self visitProgram: aRedirectingFactoryConstructorSignature
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitRedirection: aRedirection [

	^ self visitProgram: aRedirection
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitRethrowStatement: aRethrowStatement [

	^ self visitProgram: aRethrowStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitReturnStatement: aReturnStatement [

	^ self visitProgram: aReturnStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitSetOrMapLiteral: aSetOrMapLiteral [

	^ self visitProgram: aSetOrMapLiteral
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitSetterSignature: aSetterSignature [

	^ self visitProgram: aSetterSignature
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitSingleLineString: aSingleLineString [

	^ self visitProgram: aSingleLineString
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitSingleStatement: aSingleStatement [

	^ self visitProgram: aSingleStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitStatements: aStatements [

	^ self visitProgram: aStatements
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitStaticFinalDeclaration: aStaticFinalDeclaration [

	^ self visitProgram: aStaticFinalDeclaration
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitStaticFinalDeclarationList: aStaticFinalDeclarationList [

	^ self visitProgram: aStaticFinalDeclarationList
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitStringLiteral: aStringLiteral [

	^ self visitProgram: aStringLiteral
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitSwitchCase: aSwitchCase [

	^ self visitProgram: aSwitchCase
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitSwitchStatement: aSwitchStatement [

	^ self visitProgram: aSwitchStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitSymbolLiteral: aSymbolLiteral [

	^ self visitProgram: aSymbolLiteral
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitThisExpression: aThisExpression [

	^ self visitProgram: aThisExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitThrowExpression: aThrowExpression [

	^ self visitProgram: aThrowExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitTryStatement: aTryStatement [

	^ self visitProgram: aTryStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitType: aType [

	^ self visitProgram: aType
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitTypeAlias: aTypeAlias [

	^ self visitProgram: aTypeAlias
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitTypeList: aTypeList [

	^ self visitProgram: aTypeList
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitTypeName: aTypeName [

	^ self visitProgram: aTypeName
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitTypeNotVoidNotFunctionList: aTypeNotVoidNotFunctionList [

	^ self visitProgram: aTypeNotVoidNotFunctionList
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitTypeParameter: aTypeParameter [

	^ self visitProgram: aTypeParameter
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitTypeParameters: aTypeParameters [

	^ self visitProgram: aTypeParameters
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitTypedIdentifier: aTypedIdentifier [

	^ self visitProgram: aTypedIdentifier
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitUnaryExpression: anUnaryExpression [

	^ self visitProgram: anUnaryExpression
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitUri: anUri [

	^ self visitProgram: anUri
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitUriTest: anUriTest [

	^ self visitProgram: anUriTest
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitWhileStatement: aWhileStatement [

	^ self visitProgram: aWhileStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitYieldEachStatement: aYieldEachStatement [

	^ self visitProgram: aYieldEachStatement
]

{ #category : #generated }
TDartProgramNodeVisitor >> visitYieldStatement: aYieldStatement [

	^ self visitProgram: aYieldStatement
]
